language: python
python:
  - "2.7"
  - "pypy"
  
# get some stuff to install
before_install:
  - sudo apt-get install iverilog

# command to install dependencies
install:
  - pwd
  - chmod +x ./scripts/ci/install_myhdl.sh
  - ./scripts/ci/install_myhdl.sh
  - pip install Pillow

# run the test
script:
   - python --version
   - make -C test/
