language: python
python:
  - "2.7"
  - "2.6"
  - "pypy"
  
# get some stuff to install
before_install:
  - sudo apt-get install iverilog

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - chmod +x ./scripts/ci/install_myhdl_09.sh
  - ./scripts/ci/install_myhdl_09.sh
  - pip install Pillow

# command to run tests, e.g. python setup.py test
script:  nosetests
